### ISSUE TITLE
Run through API

### ISSUE THREAD

**Issue by salvinoto** [digitopvn/diginext#478]
**Is your feature request related to a problem? Please describe.**

I would like to be able to run Diginext through an API endpoint, meaning I can for example create my own interface in nextjs and make a deployment using the API.

**Describe the solution you'd like**

Either an API or npm package that makes it easy to connect your own interface to Diginext and use it headless

**Describe alternatives you've considered**
None out there

**Additional context**
None

**Comment by mrgoonie** [comment]
You can explore the docs and the api docs at: https://app.diginext.site/api-docs/

It's not really well documented, but I will try to improve it later. 

Also any PRs are welcome! 😊

**Comment by salvinoto** [comment]
Thanks I'll take a look!
