### ISSUE TITLE
[BUG] The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

### ISSUE THREAD

**Issue by salvinoto** [digitopvn/diginext#479]
**Describe the bug**
Receiving error on fresh installation:
[LOGGING 2024-02-04 11:33:24] Connecting to database. Please wait...
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at _createMongoClient (/usr/app/node_modules/mongoose/lib/connection.js:768:11)
    at NativeConnection.openUri (/usr/app/node_modules/mongoose/lib/connection.js:705:29)
    at Mongoose.connect (/usr/app/node_modules/mongoose/lib/index.js:406:15)
    at Object.<anonymous> (/usr/app/dist/modules/AppDatabase.js:26:49)
    at Generator.next (<anonymous>)
    at /usr/app/dist/modules/AppDatabase.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/app/dist/modules/AppDatabase.js:4:12)
    at Object.connect (/usr/app/dist/modules/AppDatabase.js:22:12)
    at Object.<anonymous> (/usr/app/dist/server.js:168:27)
    
    Can confirm I correctly have set the mongodb url in docker compose file.
**Using /docker-compose.podman.example.yaml**

**To Reproduce**
Start Diginext using docker compose podman in docker.

**Expected behavior**

**Screenshots**
If applicable, please run the command with `--debug` flag and add screenshots of the logs to help explain your problem & easy of investigation.
<img width="2548" alt="Screenshot 2024-02-04 at 11 47 00 AM" src="https://github.com/digitopvn/diginext/assets/54959187/82139e1d-55e9-4a7d-bb0e-c5068ee652da">

**Your environment:**
 - OS: Ubuntu
 - Node version [e.g. 16.16.0]

**Additional context**

**Are you willing to resolve this issue by submitting a Pull Request?**
- [ ] Yes, I have time & I know how to start
- [ ] Yes, I have time & I don't know where to start
- [X] No, I don't have time & I'm willing to donate for a quick fix
- [ ] No, I don't have time & I'm ok to wait for the community

**Comment by thinhfromtop** [comment]
Hi Salvinoto,

Please provide to me your env file.
DB_NAME:
DB_NAME=database_name
DB_URI follow:
DB_URI="mongodb://username:password@IP:port/database_name"

The error above may be caused by the URI not being enclosed in single quotes ('') when connecting to MongoDB.

**Comment by mrgoonie** [comment]
Did you encounter this issue while using the mongodb container config in the example yaml? 

Or you are running another mongodb container? If you are running another mongodb container and connect to it via container name in the uri, make sure your mongodb is exposed to host network.

**Comment by salvinoto** [comment]
> Did you encounter this issue while using the mongodb container config in the example yaml?
> 
> Or you are running another mongodb container? If you are running another mongodb container and connect to it via container name in the uri, make sure your mongodb is exposed to host network.

Well I originally was using the example file with the mongo db container but it wouldnt properly connect, so now I just use diginext and use digital ocean for a managed mongo db. Should I be putting quotes around the string even in the yaml

**Comment by salvinoto** [comment]
> Hi Salvinoto,
> 
> Please provide to me your env file. DB_NAME: DB_NAME=database_name DB_URI follow: DB_URI="mongodb://username:password@IP:port/database_name"
> 
> The error above may be caused by the URI not being enclosed in single quotes ('') when connecting to MongoDB.

I currently don't have an env file, I just have my docker compose file filled out 

`version: "3"
networks:
    bridge:
        driver: bridge
volumes:
    mongo:
        external: true
        name: mongo
services:
    # build server
    diginext:
        image: digitop/diginext:beta
        container_name: diginext
        working_dir: /usr/app/
        ports:
            - "6969:6969"
        restart: unless-stopped
        networks:
            - bridge
        # ----------- [START] FOR PODMAN TO RUN INSIDE DOCKER WITHOUT PRIVILEDGE MODE ----------
        devices:
            - "/dev/fuse"
        security_opt:
            - "seccomp=unconfined"
            - "label=disable"
        cap_add:
            - sys_admin
            - mknod
        # ----------- [END] FOR PODMAN TO RUN INSIDE DOCKER WITHOUT PRIVILEDGE MODE ----------
        volumes:
            # PERSIST NODE_MODULES & HOME DIR
            - /usr/app/node_modules/
            - /home/app/
            # HOST:CONTAINER
            - ./storage:/var/app/storage
        environment:
            - TZ=America/New_York
            - NODE_ENV=production
            - PORT=6969
            - BASE_URL=http://localhost:6969
            - MONGODB_CONNECTION_STRING=mongodb://username:fakepassword@IP:port/database_name
            - CLI_MODE=server
            - JWT_SECRET=********************
            - JWT_EXPIRE_TIME=48h
            - GOOGLE_CLIENT_ID=***************
            - GOOGLE_CLIENT_SECRET=**************
            - BUILDER=podman # <---- select PODMAN as a main builder here
`
