### ISSUE TITLE
[BUG] Khi roll out

### ISSUE THREAD

**Issue by DuyTranIII** [digitopvn/diginext#52]
![image](https://user-images.githubusercontent.com/125350694/224915534-293841aa-93da-4a79-8cab-3f91417e1e58.png)

![image](https://user-images.githubusercontent.com/125350694/224915643-25e32519-e4f4-43ef-9f8f-9304f6613343.png)

![image](https://user-images.githubusercontent.com/125350694/224915727-1461ef9c-9238-4783-95f3-aa409386cabf.png)

Các source sau khi build thành công tới bước roll out sẽ bị lỗi như trên

**Comment by mrgoonie** [comment]
Em chạy `dx deploy --debug` rồi chụp logs luôn nha
